[package]
name = "vmm_hid"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
vmm_devices.workspace = true
vmm_core.workspace = true
anyhow.workspace = true
ascii.workspace = true
bitflags.workspace = true
des.workspace = true
getrandom.workspace = true
slog.workspace = true
usdt = { workspace = true, features = ["asm"] }

[dev-dependencies]
tempfile = "3"
