[package]
name = "vmm_core"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
bhyve_api.workspace = true
anyhow.workspace = true
bitflags.workspace = true
libc.workspace = true
slog.workspace = true
thiserror.workspace = true
usdt = { workspace = true, features = ["asm"] }

[dev-dependencies]
serde_json.workspace = true
tempfile = "3"
