[package]
name = "vmm_machine"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
vmm_config.workspace = true
vmm_core.workspace = true
vmm_devices.workspace = true
vmm_virtio.workspace = true
vmm_boot.workspace = true
bhyve_api.workspace = true
anyhow.workspace = true
libc.workspace = true
slog.workspace = true
slog-async.workspace = true
slog-term.workspace = true
usdt = { workspace = true, features = ["asm"] }

[dev-dependencies]
tempfile = "3"
